using Npgsql;

namespace SocialNetwork;

public class Database
{
    private const string ConnectionString =
        "Host=localhost;Port=5433;Database=social-network;Username=admin;Password=admin123";

    public static NpgsqlConnection Open()
    {
        var connection = new NpgsqlConnection(ConnectionString);
        connection.Open();
        return connection;
    }

    public static void EnsureSchema()
    {
        using var connection = Open();
        using var command = connection.CreateCommand();
        command.CommandText = """
        CREATE TABLE IF NOT EXISTS Users
        (
            UserId INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            Username TEXT NOT NULL UNIQUE,
            PasswordHash TEXT NOT NULL,
            FirstName TEXT NOT NULL,
            LastName TEXT NOT NULL,
            DateOfBirth TEXT NOT NULL,
            CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        """;

    command.ExecuteNonQuery();
    }                                  
}