using Npgsql;
namespace SocialNetwork;



public class Database
{
    
    private const string ConnectionString =
        "Host=localhost;Port=5433;Database=social-network;Username=admin;Password=admin123";
    
    public static NpgsqlConnection Open()
    {
        var connection = new NpgsqlConnection(ConnectionString);
        connection.Open();
        return connection;
    }

    
    
    public static void EnsureSchema()
    {
        using var connection = Open();
        using var command = connection.CreateCommand();
        command.CommandText = """
                              CREATE TABLE IF NOT EXISTS Users
                              (
                                  UserId INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  Username TEXT NOT NULL UNIQUE,
                                  PasswordHash TEXT NOT NULL,
                                  FirstName TEXT NOT NULL,
                                  LastName TEXT NOT NULL,
                                  DateOfBirth TEXT NOT NULL,
                                  CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                              );

                              CREATE TABLE IF NOT EXISTS Friends
                              (
                                  UserId INTEGER NOT NULL,
                                  FriendUserId INTEGER NOT NULL,
                                  CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                  CONSTRAINT PK_Friends
                                      PRIMARY KEY (UserId, FriendUserId),

                                  CONSTRAINT FK_Friends_Users
                                      FOREIGN KEY (UserId)
                                      REFERENCES Users(UserId)
                                      ON DELETE CASCADE,

                                  CONSTRAINT FK_Friends_Friend
                                      FOREIGN KEY (FriendUserId)
                                      REFERENCES Users(UserId)
                                      ON DELETE CASCADE
                              );
                              """;
        
        
    command.ExecuteNonQuery();
    }

    
    
    public static void InsertUser(
        string username,
        string passwordHash,
        string firstName,
        string lastName,
        string dateOfBirth)
    {
        using var connection = Open();
        using var command = connection.CreateCommand();
        
        command.CommandText = """
                              INSERT INTO Users
                                  (Username, PasswordHash, FirstName, LastName, DateOfBirth)
                              VALUES
                                  (@username, @passwordHash, @firstName, @lastName, @dateOfBirth);
                              """;

        command.Parameters.AddWithValue("@username", username);
        command.Parameters.AddWithValue("@passwordHash", passwordHash);
        command.Parameters.AddWithValue("@firstName", firstName);
        command.Parameters.AddWithValue("@lastName", lastName);
        command.Parameters.AddWithValue("@dateOfBirth", dateOfBirth);

        command.ExecuteNonQuery();
    }



    public static void GetUsers()
    {
        using var connection = Open();
        using var command = connection.CreateCommand();

        command.CommandText = """
                              SELECT UserId, Username, FirstName, LastName
                              FROM Users;
                              """;

        using var reader = command.ExecuteReader();

        while (reader.Read())
        {
            int userId = reader.GetInt32(0);
            string username = reader.GetString(1);
            string firstname = reader.GetString(2);
            string lastname = reader.GetString(3);

            Console.WriteLine($"{userId}: {username} - {firstname} - {lastname}");
        }
    }

    
    
    public static void GetUserById(int userId)
    {
        using var connection = Open();
        using var command = connection.CreateCommand();

        command.CommandText = """
                                  SELECT UserId, Username, FirstName, LastName
                                  FROM Users
                                  WHERE UserId = @userId;
                                  """;

        command.Parameters.AddWithValue("@userId", userId);


        using var reader = command.ExecuteReader();
        
        if (reader.Read())
        {
            Console.WriteLine($"{reader.GetInt32(0)}: {reader.GetString(1)} - {reader.GetString(2)} - {reader.GetString(3)}");
        }
        else { Console.WriteLine("User not found ( "); }
    }



    public static void UpdateUser(
        int userId,
        string firstName,
        string lastName)
    {
        using var connection = Open();
        using var command = connection.CreateCommand();

        command.CommandText = """
                              UPDATE Users
                              SET FirstName = @firstName,
                              LastName = @lastName
                              WHERE UserId = @userId
                              """;

        command.Parameters.AddWithValue("@userId", userId);
        command.Parameters.AddWithValue("@firstName", firstName);
        command.Parameters.AddWithValue("@lastName", lastName);

        int rowAffected = command.ExecuteNonQuery();
        
        Console.WriteLine($"Rows affected: {rowAffected}");

    }



    public static void DeleteUser(int userId)
    {
        using var connection = Open();
        using var command = connection.CreateCommand();

        command.CommandText = """
                              DELETE FROM Users
                              WHERE UserId = @userId;
                              """;

        command.Parameters.AddWithValue("@userId",userId);
        
        int rowAffected = command.ExecuteNonQuery();
        
        Console.WriteLine($"Rows affected : {rowAffected}");
    }



    public static int? GetUserIdByUsername(string username)
    {
        using var connection = Open();
        using var command = connection.CreateCommand();

        command.CommandText = """
                              SELECT UserId
                              From Users
                              WHERE Username = @username
                              """;

        command.Parameters.AddWithValue("@username", username);

        object? result = command.ExecuteScalar();

        if (result == null)
        {
            return null;
        }
        
        return (int)result;
    }



    public static void AddFriendshipPair(int userId, int friendUserId)
    {
        using var connection = Open();
        using var transaction = connection.BeginTransaction();
        
        using var command = connection.CreateCommand();

        command.Transaction = transaction;

        command.CommandText = """
                              INSERT INTO Friends (UserId, FriendUserId)
                              VALUES (@userId, @friendUserId);

                              INSERT INTO Friends (UserId, FriendUserId)
                              VALUES (@friendUserId, @userId);
                              """;

        command.Parameters.AddWithValue("@userId", userId);
        command.Parameters.AddWithValue("@friendUserId", friendUserId);

        try
        {
            command.ExecuteNonQuery();

            transaction.Commit();
        }
        catch
        {
            transaction.Rollback();
            throw;
        }
    }



    public static void ListFriends(int userId)
    {
        using var connection = Open();
        using var command = connection.CreateCommand();

        command.CommandText = """
                                 SELECT u.UserId,
                                        u.Username,
                                        u.FirstName,
                                        u.LastName
                                 FROM Friends f
                                 INNER JOIN Users u
                                    ON f.FriendUserId = u.UserId
                                 WHERE f.UserId = @userId
                                 """;

        command.Parameters.AddWithValue("@userId",userId);

        using var reader = command.ExecuteReader();

        while (reader.Read())
        {
            int friendId = reader.GetInt32(0);
            string username = reader.GetString(1);
            string firstName = reader.GetString(2);
            string lastName = reader.GetString(3);
            
            Console.WriteLine($"{friendId}: {username} - {firstName} {lastName}");

        }
    }



    public static void ListUsers(int userId)
    {
        using var connection = Open();
        using var command = connection.CreateCommand();

        command.CommandText = """
                              SELECT u.UserId,
                                      u.Username,
                                      u.FirstName,
                                      u.LastName,
                              CASE 
                                  WHEN f.FriendUserId IS NOT NULL THEN 'Friend'
                                  ELSE 'NOT FRIEND'
                              END AS FriendshipStatus
                              FROM Users u
                              LEFT JOIN Friends f
                                  ON f.FriendUserId = u.UserId
                                  AND f.UserId = @userId
                              
                              """;

        command.Parameters.AddWithValue("@userId",userId);

        using var reader = command.ExecuteReader();

        while (reader.Read())
        {
            int userIdFromDatabase = reader.GetInt32(0);
            string username = reader.GetString(1);
            string firstName = reader.GetString(2);
            string lastName = reader.GetString(3);
            string friendshipStatus = reader.GetString(4);
            
            Console.WriteLine($"{userIdFromDatabase}: {username} - {firstName} {lastName} {friendshipStatus}");

        }

    }
}